### ISSUE TITLE
Flex TV Can't Find Cast Plugin

### ISSUE THREAD

**Issue by balter-io** [d8ahazard/Cast.bundle#12]
@I have Plex installed on a Synology DS1817+ with Phlex running in a docker container. I have tried to install the cast.bundle plugin manually and via Webtools however Flex tv can never find it (it always finds the chrome browser I use). I'm definitely no software guru but it seems the plugin keeps crashing so is unreachable by Flex. The logs only show that there is no plugin found. 

1242 [Sat, 23 Jun 2018 22:48:34 +0000] [ERROR] [a5pire][index::makeBody:makeMetaTags:getUiData:scanDevices] - NO PLUGIN DETECTED!!

I am also unable to link my google account with Flex TV.

my.serverip.address is not a publicly accessible address.{"speech":"Unable to look up user.","contextOut":[{"name":"playmedia","lifespan":2,"parameters":[]}],"data":{"google":{"expectUserResponse":false,"isSsml":false,"noInputPrompts":[],"richResponse":{"items":[{"simpleResponse":{"textToSpeech":"Unable to look up user.","displayText":"Unable to look up user."}}]}}}}

Would really appreciate some help regarding this @

**Comment by d8ahazard** [comment]
Please check out https://github.com/FlexTV.bundle for the latest iteration of the plugin.

Also, there's an experimental stand-alone app for homes without a PMS server, but you want to control cast devices at https://github.com/d8ahazard/FlexConnect - and docker - https://github.com/d8ahazard/docker-FlexConnect

If you have issues, feel free to report them there!
