### ISSUE TITLE
Not showing all cast devices

### ISSUE THREAD

**Issue by arturolaguna** [d8ahazard/Cast.bundle#13]
Installed cast.bundle with webtools and works great on Google mini speaker it won't recognize video Chromecast. Any help?

**Comment by spicerackk** [comment]
Same here, even if I change the rescan frequency, it doesn't ever show up any of my GH speakers, and only one CC if I'm lucky. There was a point last night where it had shown them all after having Flex TV webapp open for 2 or so hours. 

Also side note, does Flex TV need to be open constantly for it to work? Stupid question, I know.

**Comment by LoudSoftware** [comment]
~~Even worse for me, all it sees is chrome, not my tv or my home mini~~

Edit: Fixed it by running it in a docker container instead of using the webapp.
I couldn't/didn't want to run the container because I couldn't reach the page even though I allowed 5666 through ufw. Disabling UFW alright solved the problem

**Comment by d8ahazard** [comment]
You might want to check firewall settings on the server hosting the cast.bundle. If windows firewall is enabled, PlexScriptHost.exe should be fully allowed on your local 'private' LAN.

@spicerackk - No, Flex TV doesn't need to be open to work. The web UI is just for configuration and testing.

**Comment by ezar** [comment]
using cast.bundle inside plex docker, only detect Chrome device. At home we have: Chromecast, Google Home, ... why?

**Comment by d8ahazard** [comment]
You need to have ports open for multi cast, udp 5353.

**Comment by ezar** [comment]
I’m using --net=host - Shares host networking with container.

**Comment by mrtruebeliever** [comment]
I'm having the same problem I guess. Chrome web app en the app on my phone are found when scanning, but my 2 chromecasts do not show up.

Installed the plugin in the freenas plex jail. When I try to rescan devices in the plex plugin UI, it gives me the error "Plugin not responding."

Don't know how to check if the ports for multicast are open or not on that jail?

**Comment by chumleyex** [comment]
I'm in the same boat. I have Phlex in docker, it sees Plex when it's open in chrome, but doesn't see my chromecast or mini. When I go into plugins for plex, I open Devices and it says the Plugin in not Responding. Port 5666 is open and this is accessible from the internet via a reverse proxy.

**Comment by d8ahazard** [comment]
Please check out https://github.com/FlexTV.bundle for the latest iteration of the plugin.

Also, there's an experimental stand-alone app for homes without a PMS server, but you want to control cast devices at https://github.com/d8ahazard/FlexConnect - and docker - https://github.com/d8ahazard/docker-FlexConnect

If you have issues, feel free to report them there!
