### ISSUE TITLE
Install castplugin in firestick

### ISSUE THREAD

**Issue by daveplotty** [d8ahazard/Cast.bundle#19]
Is it possible as I view Plex through my phone and firestick using a remote server not a local one.

**Comment by d8ahazard** [comment]
Please check out https://github.com/FlexTV.bundle for the latest iteration of the plugin.

Also, there's an experimental stand-alone app for homes without a PMS server, but you want to control cast devices at https://github.com/d8ahazard/FlexConnect - and docker - https://github.com/d8ahazard/docker-FlexConnect

If you have issues, feel free to report them there!
