### ISSUE TITLE
Remote Plex

### ISSUE THREAD

**Issue by Kedryn** [d8ahazard/Cast.bundle#20]
Does this addon work only over lan? I have a plex server on a VM abroad, and from what i've understood, Cast will not detect clients. Am i right?

**Comment by d8ahazard** [comment]
This should have no issue working on a remote server.

**Comment by Kedryn** [comment]
I've installe Phlex on a local rasberry in lan, and it's working. It's reachable from outside. It's linked to Google and the test is ok.
I've installed Cast.bundle on my Plex that lies in a VM in another nation. The plugin runs fine. 
BUT
It can't find any device. I was wondering how a plugin in another network could be able to find devices in my lan...

**Comment by d8ahazard** [comment]
Yeah...no, that's not how it works. Sorry if I was confusing. The plugin
should be on a Plex server on the same LAN where your devices to be
controlled are.

Now, if the VM in another country is on a LAN with some devices that are
cast/plex clients, Flex TV would see those devices as well. The plugin
basically overcomes the hurdles of trying to control devices from outside
the LAN. It leverages the connectivity stuff in Plex to where, if your Plex
is remotely connectable, Flex TV should be able to use it.

Make sense?

**Comment by LckyLuciano** [comment]
I'm also in a similar situation.  My Plex server is remotely hosted in a data-center, but my devices are local here in my house.  The Cast plugin installs fine remotely but can't see any of my devices.   Are there any plans to support this type of setup or allow a user to manually configure a device?

**Comment by d8ahazard** [comment]
Presently, no. The easiest solution would be to spin up a PMS server on
something...anything...local, install the plugin.

As far as manually configuring a device...also not in the cards. There's
too many things going on in the background to do this reliably, and it kind
of defeats the purpose...

However, sometime in the future, the Cast plugin will be supplanted by a
stand-alone application that serves this purpose.

**Comment by d8ahazard** [comment]
Please check out https://github.com/FlexTV.bundle for the latest iteration of the plugin.

Also, there's an experimental stand-alone app for homes without a PMS server, but you want to control cast devices at https://github.com/d8ahazard/FlexConnect - and docker - https://github.com/d8ahazard/docker-FlexConnect

If you have issues, feel free to report them there!
