### ISSUE TITLE
Chooses incorrect IP for server

### ISSUE THREAD

**Issue by jofu** [d8ahazard/Cast.bundle#21]
The cast plugin is choosing the incorrect IP to give the chromecast. I have two interfaces on my server, but the wrong one is being chosen. I didn't see somewhere I could configure or steer it so I hardcoded the correct IP and it works. Some sort of config to override if the automatic discovery fails might be nice.

**Comment by d8ahazard** [comment]
Please check out https://github.com/FlexTV.bundle for the latest iteration of the plugin.

Also, there's an experimental stand-alone app for homes without a PMS server, but you want to control cast devices at https://github.com/d8ahazard/FlexConnect - and docker - https://github.com/d8ahazard/docker-FlexConnect

If you have issues, feel free to report them there!
