### ISSUE TITLE
"https://github.com/FlexTV.bundle" Not Working

### ISSUE THREAD

**Issue by fiservedpi** [d8ahazard/Cast.bundle#25]
when trying to go to the new cast plug-in the page is erroring out 

![image](https://user-images.githubusercontent.com/42981853/57196417-b3f50680-6f2a-11e9-94a2-b00803378e70.png)

**Comment by d8ahazard** [comment]
Yeah, it would help to provide the right URL. Sorry about that...

https://github.com/d8ahazard/FlexTV.bundle
