### ISSUE TITLE
no response 

### ISSUE THREAD

**Issue by geertvercamer** [d8ahazard/Cast.bundle#5]
Hi,

I installed the bundle via webtools and it shows fine in Plex/Channels. I see the devices, the broadcast test works ok (that is, the 2 devices broadcast the normal sound, nothing else).
When I visit the page http://xxx.xxx.xxx.xxx:32400/chromecast/Devices?X-Plex-Token=......... I get an 404 error.
Any ideas?

Thanks!

Kind regards,

Geert

**Comment by fcastilloec** [comment]
~~I'm having the same problem, anybody care to comment what's going on?~~

EDIT: After some trial and error, the address to see the list of devices is: http://server:32400/chromecast/resources?X-Plex-Token=token

Now I have to figure out how to play a specific item...

**Comment by d8ahazard** [comment]
What happens when you try the plugin UI in Plex?

**Comment by fcastilloec** [comment]
I can see the list of devices under the plugin UI in Plex, but I want to use your plugin with my own program so I needed a URL that I can ask for a list of devices and play specific media.

BTW, when selecting my chromecast through the plugin UI (/Devices) I get: "This plugin is not responding"

**Comment by d8ahazard** [comment]
Please check out https://github.com/FlexTV.bundle for the latest iteration of the plugin.

Also, there's an experimental stand-alone app for homes without a PMS server, but you want to control cast devices at https://github.com/d8ahazard/FlexConnect - and docker - https://github.com/d8ahazard/docker-FlexConnect

If you have issues, feel free to report them there!
